# Generated by Django 3.2.16 on 2022-11-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
